### ISSUE TITLE
Music Appearing Wonky

### ISSUE THREAD

**Issue by nxllxvxid** [tedhinklater/finality#19] opened 2024-06-24 05:26 UTC
I really don't know how else to describe it other than that:
![image](https://github.com/tedhinklater/finality/assets/19805594/3dde6156-cac3-4535-895e-a540ee9ddd71)
And that is at 100% normal zoom, it looks worse the more you zoom in, such as the albums on the right side colliding with the song names of the currently viewed album. It also looks wonky for a single song too:
![image](https://github.com/tedhinklater/finality/assets/19805594/33d40888-de41-42c7-8b86-60301976a72c)

Another example:
![image](https://github.com/tedhinklater/finality/assets/19805594/12569736-bfbd-40c7-940b-152db8b69aec)

Another:
![image](https://github.com/tedhinklater/finality/assets/19805594/a14699b2-6c6f-4b35-bec2-3bddc8d36b34)

**Comment by tedhinklater** [comment] 2024-06-24 10:02
Thanks for the heads up I'll fix the music view next

**Comment by nxllxvxid** [comment] 2024-06-24 13:00
> I've only designed it for 1080p/16:9 at 100% zoom, like a fixed TV view, but I'll do what I can

ah that could make a difference I do use a 1440 monitor

**Comment by tedhinklater** [comment] 2024-06-24 13:23
Here I am with my tv from 2007 haha. 

![music album](https://github.com/tedhinklater/finality/assets/66086488/1cde4b60-5aa5-480d-a610-b0e21431e004)
![music artist](https://github.com/tedhinklater/finality/assets/66086488/16598680-816a-4cfb-9deb-6a4278ce3ac6)

I hope this is a bit cleaner. I'll try to make a layout for different ratios/resolutions, I just have to figure out how...

**Comment by nxllxvxid** [comment] 2024-06-24 16:29
> Here I am with my tv from 2007 haha.
> 
> ![music album](https://private-user-images.githubusercontent.com/66086488/342352950-1cde4b60-5aa5-480d-a610-b0e21431e004.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyNDUxODIsIm5iZiI6MTcxOTI0NDg4MiwicGF0aCI6Ii82NjA4NjQ4OC8zNDIzNTI5NTAtMWNkZTRiNjAtNWFhNS00ODBkLWE2MTAtYjBlMjE0MzFlMDA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDE2MDEyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5MWRmNGU2MGMxYzc3MGNlYmY1MWVjOTJmYWI1NWM0MTQxNTlhNTI1NWE4MzllNDc0ODNmNDliYzhlZmZiNzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pzKmZ0BMbcO-5qmcJy3IxeD2NtE4lsznrlGRch01qeI) ![music artist](https://private-user-images.githubusercontent.com/66086488/342352965-16598680-816a-4cfb-9deb-6a4278ce3ac6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyNDUxODIsIm5iZiI6MTcxOTI0NDg4MiwicGF0aCI6Ii82NjA4NjQ4OC8zNDIzNTI5NjUtMTY1OTg2ODAtODE2YS00Y2ZiLTlkZWItNmE0Mjc4Y2UzYWM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDE2MDEyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4Y2RhM2QxZjRmM2MxOGE3YWRkOTNjMDEzYjI1YjliNDJkNzRiOWVjZjMxMTI5Y2EwODlmZmVhZDFmZGQzMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Hfh28-4DbphOAxPNTcQZ8g1EJWFAgXE3iEvKtgsHrVI)
> 
> I hope this is a bit cleaner. I'll try to make a layout for different ratios/resolutions, I just have to figure out how...

It is looking a lot better in the album view the only issue is the scrollbar clipping now:
![image](https://github.com/tedhinklater/finality/assets/19805594/be420022-09e6-41c4-9637-6fb9a8f5c19b)

**Comment by tedhinklater** [comment] 2024-06-24 18:16
Thanks for catching the scrollbar clipping, it's fixed now, and thanks for taking the time aswell. 

> Maybe as apposed to have the similar albums on the ride side you can make them reset under the album cover on the left similar to the seasons for tv shows?

Nice idea but the problem is, in Jellyfin, the Similar Albums section is the "More Like This" section in disguise, so it would put similar movies/shows under the movie cover too. You move one thing and it moves something else on another page! But I will do what I can! Thanks again

**Closed** 2024-06-25 00:31 UTC

**Comment by nxllxvxid** [comment] 2024-06-28 12:36
> Thanks for catching the scrollbar clipping, it's fixed now, and thanks for taking the time aswell.
> 
> > Maybe as apposed to have the similar albums on the ride side you can make them reset under the album cover on the left similar to the seasons for tv shows?
> 
> Nice idea but the problem is, in Jellyfin, the Similar Albums section is the "More Like This" section in disguise, so it would put similar movies/shows under the movie cover too. You move one thing and it moves something else on another page! But I will do what I can! Thanks again

Honestly it's no problem I can literally help you with making it good for 1440 if you want me to. I love this theme it's beautiful and I'd love to see it work good for all resolutions yk?

**Comment by nxllxvxid** [comment] 2024-06-28 13:01
> > Honestly it's no problem I can literally help you with making it good for 1440 if you want me to by showing you my end (my css knowledge is so limited). I love this theme it's beautiful and I'd love to see it work good for all resolutions yk?
> 
> Thanks you so much, yeah I need to figure out how to design for different resolutions/ratios on my 1080p screen. I'll give it a try, and if you can tell me if it worked or not, that would be super appreciated. Is your screen 16:9 by the way? Or ultrawide

it is 16:9
